### PR TITLE
Change initial stack size to 16 from 200.

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by petermattis** [comment]
I messed this up while addressing the PR comments on the previous change.

**Comment by tamird** [comment]
Heh, I didn't understand why this is "initial", but now I see what looks like a reinventing of `append`: https://github.com/cockroachdb/yacc/blob/pmattis/initial-stack-size/yacc.go#L3497:L3510

**Comment by tamird** [comment]
LGTM

**Comment by petermattis** [comment]
I don't know what the code is reinventing `append`.

**Pull request merged**
